:::{.callout-important}
注意：本網站尚在編輯中，欲閱讀本書全文請至 <https://cbetaonline.dila.edu.tw/zh/X0367>

:::

# 卷首 {.unnumbered}

## 序文

昔長水大師。詮解首楞嚴經。講演之日。天雨寶華。其箋疏之地。賜額楞嚴講寺。人稱其疏義。語簡而義豐。事詳而理密。薈撮有唐惠振。慤沇^[慤音卻，誠實；沇音眼，水流動貌]諸家之長。含攝賢首五教。起信五重之要。箋解名家至今推之。廣度法師。嗣法賢首。荷擔教宗。任講席者三十餘載。予延主栴檀方丈。缾華鉢水。蕭然掩關。肆力詮解。數年於茲。都人士雅重。久以為長水之儔也。以本生心地觀經。文言流暢。旨趣幽深。自唐迄今。未有疏解。因攷證羣經。融會諸論。精研靜想。印以一心。發科起分。準長水楞嚴義例。著成疏解十一卷。乃深自謙抑。名曰淺註。而請序于予。 

予觀其首疏四恩言。君臣父子之際。如疎鐘警曙。孤角吹霜。不自知其感發之深也。至無垢性阿蘭若諸品。如古木寒蟬。空山清磬。惘然若失者久之。及夫觀心而真諦現前。瘥病而空有雙泯。則秋月獨明。寒江逈碧。超然立塵滓之表矣。茲義出。將雨華賜額復見於今。然猶曰淺註。豈尚有待夫後賢之鈎深晰奧者耶。是非予所知也。 

經云。是經福力難思。能令所在國土豐樂。則疏經之功。誠足裨國家聖治於無疆。寧僅度諸有情。普證無上正等菩提。以弘報佛恩而已哉。故不辭而序之如此。 

康熈丁丑歲仲春穀旦  

:::{.text-right}
和碩莊親王序
:::

<br></br>

嘗觀佛之有經。其寓義也甚微。其闡道也至大。大則天地皆為所包容。微則空色悉歸於一致。所以然者。端在勤修心地。以觀想於神化而無餘。是故大鈔諸經。性相等論。極洪慈之無際。示秘悟之多方。而心即是佛。佛即是心。斯言洵稱明鑒也。但口誦經藏。而輒礙迷津。身受法戒。而真元不悟。懸擬菩提。昏如長夜。自非經篆之玄機。不足以開悟禪宗也。亦以奧義未窮。沉淪誤墮。則註經之有功於佛氏。豈淺鮮哉。廣度法師。博覽羣經。鈎深握要。體賢首之成訓。運一己之神明。萬理歸懷。不同浮響。應緣闡教。高竪法幢。三十年來。未嘗輟席。庶幾不辜其志。而躬膺大道矣。獨心地觀一經。旨趣淵源。渺無疏釋。法師所以持心攻苦。考諸經論。積之三載。而註解始成。丙子孟秋。將付剞劂^[音几決，刻書]。請序於予。予固知佛教精微。經言秘邃。如窺天而莫測其高也。如探海而莫窮其際也。又安得以管見而妄置一詞乎。及閱其註釋。理若珠聯。義同璧合。不禁拊心稱快。曰至矣盡矣。經之纖悉畢出矣。參玄入道。較若指掌矣。使非修心地以神其觀想。由觀想以融其心地。而無機不徹也。又烏能臻此。由是而益知經義之大。可以包容天地矣。經義之微。可以渾然色相矣。即舉大鈔諸典。性相旨趣。以及波羅蜜之三根九品。無上道之一德四行。而了然心佛萬殊一貫。法師不誠大覺中人乎。敬具俚言。罔慚固陋。亦以表揚佛訓。道垂不朽。炳若日星。以俟眾生之自悟焉。云爾。

康熈三十五年歲次丙子孟秋吉旦

:::{.text-right}
原爵多羅惠王半龕主人敬題
:::

<br></br>

## 心地觀經淺註本序

余於齠齓^[音條趁，七、八歲換牙時]。知有此經。既入空門。間一繙閱。始知文言流暢。旨趣幽深。欲識玄微。輒茫然無是處。蓋不得義意所在云。遂徧參知識。親近講肆者無虗日。每大鈔諸經。性相等論。無所不聽。獨此一經。不得而聞焉。何也。良由不得疏解故也。是以教家不傳。人罔解義。因感慨繫念。意欲解釋。以利器未成。徒增慚愧耳。由是博覽群經。神會諸論。時將捉筆。猶為講席所累。三十年來未果其願。所謂法不虗應。應必有時。

于癸酉春。客席之暇。仍再究神會。豁然貫通。悟知心地法門。截流到岸。一念薰修。即心是佛。所以經云。此心地法門。一經耳根。攝念觀心。薰菩提種。不久得成無上菩提。又云。三界之中以心為主。能觀心者究竟解脫。不能觀者究竟沉淪。是知心地觀門。廼修行之關鍵。入道之樞機。故佛之成與不成。但在觀心之能與不能耳。良以一切眾生俱有如來智慧德相之心地。以物欲妄想所蔽而不自知。故懷寶迷邦。抱珠乞丐。聖人觀之。誠為可愍者也。於是世尊將欲啟發此心。指示令悟。先說四恩應報。欲明真諦。故就世諦以正此心也。次說廣讚出家。既明世諦。故就真諦以決其志也。無垢性。阿蘭若。調伏其妄。而攝持其真也。樂遠離行。警策恐怖。治此心也。彌勒慈尊廣求觀門。修此心也。及乎波羅蜜三根九品。復警以真師難遇。無上道一德四行。而皆會為功德莊嚴。觀心助神呪。若萬病愈於阿伽。成佛託印觀。如風帆揚於順水。菩提心心即菩提。金剛甲甲為心用。自他兼利。一世功成。至哉不可得而思議者。其惟頓教法門歟。

嗚呼。時丁末法。邪說多岐。權衡正見。賴有斯存。且又隱於藏函。未獲弘通。余故不揣膚受。謬為疏解。聊一隙明。以光法施。敢望同志共報佛恩云爾。

時 大清康熈三十五年 歲次丙子孟秋 佛歡喜日

:::{.text-right}
京都栴檀禪林傳賢首宗第二十八世 雲中來舟 序於觀旨法堂并書
:::