# 大乘本生心地觀經淺註懸示 {.unnumbered}

:::{.text-right}
神京外栴檀寺沙門　來舟述
:::

:::{.text-sectioning}
△將釋經義總啟十門。初教起因緣。
:::

將釋經義總啟十門。一教起因緣。二藏教所攝。三義理分齊。四教所被機。五能詮教體。六宗趣通別。七品目次第。八傳譯時年。九總釋名題。十別解文義

夫十門通判者。始於賢首。富於清涼。然隨經定義。各有廣略。如華嚴懸談。彌陀疏鈔。概可知也。今則列名遵古。開章從省焉。

夫十門生起者。謂聖人設教必有由致。故受之以教起因緣。教理既陳。屬何藏乘。故受之以藏教所攝。既知歸屬。義理如何。故受之以義理分齊。義理既明。未委何被。故受之以教所被機。已知所利。猶迷能詮。故受之以能詮教體。能詮既悟。尚昧宗歸。故受之以宗趣通別。雖識趣向。未審品目。故受之以品目次第。既知品目。未明傳譯。故受之以傳譯時年。教義既知。未明綱要。故受之以總釋名題。雖明題意。臨文難辨。故受之以別解文義。前八義門。後二解經。與天台五重玄義。少有詳略。義如貫索。用釋眾經。皆同意也。

第一教起因緣者。言聖人設教之所為也。然有總別。總則通於一大時教。酬因酬請。顯理度生。諸經皆是也。法華云。諸佛世尊。為一大事因緣故。出現於世。開示悟入佛之知見。即諸經之總緣。此經以心地觀門入佛知見。別局當經。略示十種。一警策凡迷。自知因果故。二直示法界。不離心地故。三引諸凡小。修習佛智故。四顯四恩應報。引發菩提故。五挽回邪逆。令信正法故。六示菩薩行。較量難易故。七十度兼修。自他兩利故。八降伏妄心。薰修正觀故。九正明蘭若。斷疑生信故。十顯密並陳。疾成佛果故。

第一警策凡迷。自知因果者。夫源清流潔。形端影直。善惡之報。果因不異。現前易見者。如形影源流。雖愚亦信而不疑。隔世難通者。如善惡因果。在智猶疑而難信。故我世尊將說此經。以同體智光。圓照法界。現生佛之始終。明善惡之趣向。使在會者。見相而警心。自信而不疑也。

二直示法界。不離心地者。三界唯心。眾生迷而不識。萬法唯識。諸佛證而自知。故佛放光明洞然法界。將示情器之萬殊。不離生佛之方寸。此世尊萬德吉祥紋。放光表法之正意也。

三引諸凡小。修習佛智者。凡為六道生靈。小謂二乘權教。通迷一等之心地。終纏二種之生死。故我世尊直指妙心。開通真觀。欲令凡外權小。齊證菩提涅槃。經云。我今演說心地法門。引導眾生。令入佛智是也。

四顯四恩應報。引發菩提者。大道悠弘。小機聞而河漢其言。曲成易見。常士受而苟就其事。故我世尊先陳四恩應報。為投機之談。引勸菩提應發。為究竟之說。經文。即度五百長者。始終因緣是也。

五挽回邪逆。令信正法者。背正道之謂邪。忤父母之謂逆。此實造業之機。墮苦之緣也。故我世尊示正見以轉邪。開孝道以回逆。此則去禍因之惡積。啟善以之緣昇。經文即智光長者子因緣是也。

六示菩薩行。較量難易者。發兩利之心者。曰菩薩。即佛果因地之名也。然心無不同。操修或異。故我世尊明示曲直。言在家出家之不同。故指蘭若清淨。靜修則易。居家煩冗。入道則難。經文即阿蘭若。離世間等品。皆此意也。

七十度兼修。自他兩利者。鵬程海運。則九萬可圖。道假行門。則三祗易越。自利利他。菩薩之道。六度十度。菩薩之乘。必也去在家而居蘭若。方為真實。去塵勞而就清淨。便易初心。經文即波羅蜜品。彌勒所問是也。

八降伏妄心。薰修正觀者。妄心為生死之機。正觀為入道之門。背正觀而逐妄心者。即六道之凡夫。伏妄心而入正觀者。即三乘之聖賢。良由觀有權實。故乘分小大之別。今則直指心地。標名正觀。妄心歇處即菩提。觀慧明時同法界。經云。三界之中以心為主。能觀心者。究竟解脫等是也。

九正明蘭若。斷疑生信者。佛雖明示蘭若。為修行菩提道者所當依止。惟恐信受不篤。故引證諸佛菩薩。從此修證而得道果。所以盡大眾之餘疑。而增明樂欲之心也。經云。十方諸佛所依故。三世諸佛得道故。皆是意也。

十顯密並陳。疾成佛果者。上根利智之人。直一蹴而臻聖城。慧淺業重之機。必雙修而祛惑障。故我世尊顯密並陳。正助齊舉。欲使利鈍之流。皆入心地之觀。經文。明手印真言處。皆此意也。以上教起因緣竟。

:::{.text-sectioning}
△二藏教所攝二。初明藏攝。
:::

二藏教所攝者。先明藏攝。次明教攝。今初明藏有二。一三藏。二二藏。藏者。以含攝故。謂攝一切所應知義。三藏者。一修多羅藏。二毗奈耶藏。三阿毗達磨藏。

今初修多羅。亦名修妬路。亦名素呾纜。皆梵音楚夏。義無異也。古德譯為契經。謂上合諸佛之心。下孚眾生之性。故曰契理合機之經也。經有多義。會之不出貫攝常法。貫謂貫穿義理。攝謂攝持根機。常謂諸佛不易之道。法謂天下共遵之規。此略存兩方。省取四義。餘繁。不能徧及。

二毗奈耶藏者。亦名毗尼。梵語之具略耳。此翻為調伏。調謂練三業而欲淨。即作持也。伏謂制諸惡而不行。即止持也。就所詮之行彰名。故云調伏之藏。或翻毗尼為滅。言滅業非。滅煩惱得滅果。梵語又名尸羅。或云翅呾羅。此翻清涼。謂離生死之熱惱。證寂滅之清涼。或亦名波羅提木叉。此云別解脫。此皆律藏之異名也。

三阿毗達磨藏者。阿毗譯對。達磨譯法。法有二種。一名勝義法。即涅槃常住之理也。二名法相法。即四聖諦之相也。然所對之法既二。能對之慧亦二。一者對向。向前涅槃。二者對觀。觀前四諦。由對果對境。故名對法。葢即論之通稱。以所詮而立名。舊譯為無比法。以詮勝慧立名。亦名優鉢提舍。此云論議。以佛法至理。假論議而詳明。慧悟所由生也。以能詮之體立名。

以上三藏者。攝盡一大時教。該通大小諸乘。考其所詮。各有通局。就局而言。經詮定學。律詮戒學。論詮慧學。以通言之。各相交攝。今此經者正屬修多羅藏攝也。傍亦兼屬二藏。若以經攝藏。三藏具含。以三卷頌中說戒故。彌勒難問有論議故。

二二藏者。一聲聞藏。二菩薩藏。由前三藏開為二乘。詮小乘者。名聲聞藏。詮大乘者。名菩薩藏。莊嚴論云。此三藏。由上下乘別故。復為聲聞藏及菩薩藏。若約乘分藏。理宜為三。由辟支不借教故。出有佛世。聲聞攝故。所以分二。今此經者為菩薩藏攝。以此攝彼。二皆具含。亦有聲聞名行故。

:::{.text-sectioning}
△二明教攝二。 初不分教。
:::

二教攝者。夫教海冲深。法雲彌漫。智光無際。妙辯叵窮。以無言之言。詮絕言之理。以無說之說。酬無盡之機。極位所承。凡情難挹。今乘理教之力。略明開合之端。如西域東夏弘闡之者。於一代聖言。或開宗分教。或直釋經文。各隨所見。咸有據焉。其不分之義有五。一理本一味。殊途同歸故。二一音普應。一雨普滋故。三原聖本意。為一大事故。四隨一一文。眾解不同故。五多種說法成枝流故。以斯五義。故不可分。竊恐情搆異端。是非競作。故以不分為得也。

:::{.text-sectioning}
△二分教二。初此方。
:::

其分教者。亦有多義。一理雖一味。詮有淺深。故須分之。使知權實故。二約佛雖是一音。就機差而教別故。三本意未申。隨他意語而有異故。四言有通別。就顯說故。五雖分權實。須知佛意有開顯故。以斯多義。開則得多而失少。合則得少而失多。但能虗己求宗。不可分而分之。亦何傷於大旨。故今分之。

西天東土。分判諸師。略舉數家。以備觀覺。先明此方。勒為五門。

第一立一音教者。有二師。一後魏菩提流支。言如來一音。同時報萬。大小並陳。二姚秦羅什法師。言佛一圓音。無思普應。機聞自殊。上之二師。前則佛音具異。後則異自在機。各得圓音之一義。俱是不分之意也。

第二立二教者。一西秦曇牟讖三藏。立半滿教。以半字教謂聲聞藏。說理未圓。若字之有半故。二滿字教。謂菩薩藏。談理滿足。若字之圓滿故。此依涅槃經半滿之義。兼幼子學書之喻。故有是判。又隋朝遠法師。亦同此立。二隋朝延法師。立漸頓教。一漸教。約漸悟機。大由小起。所設具有三乘之教。二頓教。約頓悟機。直入於大。不由於小。頓令得道也。然此雖約機。說有漸頓。而所說法不出半滿。三唐初海印法師。亦立二教。一屈曲教。二平道教。屈曲者。謂釋迦如來所說之經。逐其機性。隨計破著。方便委曲。令物生解。如涅槃經。雖說圓通一極之理。或對權顯實。或會異歸同。故名屈曲教。平道者。謂盧舍那所說之經。隨其法性。平等而說。如華嚴經。雖有隨機。各別調伏。皆是稱性善巧。一時頓演。故名平道教。四齊朝隱士劉虬。亦判二教。一漸教。始自鹿苑。終至雙林。從小至大。故名漸教。二頓教。謂佛最初說華嚴。如日初出先照高山。故名頓教。

第三判三種教者。亦有三家。一南中三教。謂齊朝已後。江南諸師立此三教。判如來一代所說之法也。一漸教。二頓教。此全同劉虬。但加不定教。由漸中先小後大。而央崛經六年之內即說。為遮此難。故立不定。謂別有一經。雖非頓攝。而明佛性常住。即勝鬘金光明等。是為偏方不定教也。漸中開合。諸師不同。或但為二。即是半滿。或分為三。即武丘山岌法師。謂十二年前。見有得道。名有相教。十二年後。齊至法華。見空得道。名無相教。最後雙照一切眾生佛性。闡提作佛。名常住教。此與唐三藏三時之教大同。真諦三藏。西印土人。依金光明經。立轉照持三輪之教。亦大同此。而時節小異。謂七年前說四諦。名轉法輪教。七年後說般若。具轉照二輪教。以空照有故。三十年後。具轉照持三輪教。以雙照空有。持前二故。或分為四。即宋[^song]朝岌法師。謂於前三時。無相之後。常住之前。指法華為同歸教。以會三歸一。萬善悉向菩提故。或開為五。然有二家。一道場慧觀法師等。於無相之後。同歸之前。指淨名思益等。為抑揚教。二者即前劉公。不開抑揚。而有教之初。取提謂經^[即提謂波利經]為人天教。

[^song]: 劉宋

二後魏光統律師。承習佛陀三藏。亦立三教。謂漸頓圓。初為根未熟者。先說無常。後方說常。先空後不空等。如是漸次。故名為漸。二為根熟之輩。於一法門。具足演說。常無常。空不空等。一切具說。更無由漸。故名為頓。三為於上達。分階佛境之者。說於如來無礙解脫。究竟果德。圓極祕密。自在法門。故名為圓。此亦約化儀。說有前後耳。意明今時堪受頓者。必昔曾受化。故云根熟。上達之言。義兼地前。分階佛境。即謂地上。

三隋末唐初吉藏法師。依法華第五。立三種法輪教。一始見我身。聞我所說。即皆信受。入如來慧。即根本法輪教。二除先修習學小乘者。即枝末法輪教。三我今亦令得聞是經。入於佛慧。即攝末歸本法輪教。

第四立四教者。略有四家。一梁朝光宅法師。依法華第二。立四乘教。謂臨門三車。即是權教三乘。四衢等賜。即實教大乘。以臨門牛車。亦同羊鹿俱不得故。並無體故。諸子皆索故。是知三皆虗指。以為方便。此則前三是三乘。後一是一乘。

二陳隋二代天台智者。承南岳思大師立四教。云一三藏教。此教明因緣生滅四真諦理。正教小乘。傍化菩薩。二通教。通者同也。三乘同稟故。此教明因緣即空。無生四真諦理。是摩訶衍之初門。正化菩薩。傍通二乘。大品云。欲得聲聞乘。當學般若波羅蜜等。然教理智斷。行位因果。皆通淺深。不同於共般若。唯共於淺。三別教。別即不共。不共二乘人說故。此教正明因緣假名。無量四真諦理。的化菩薩。不涉二乘。故聲聞在座。如聾如盲。不名不共。而云別者。兼欲揀非圓故。以一因逈出。一果不融。歷別而修。不得因果圓融故。四圓教。圓以不偏為義。此教正明不思議因緣。二諦中道。事理具足。不偏不別。但化最上利根之人。故名為圓。華嚴經云。顯現自在力。為說圓滿經。無量諸眾生。悉受菩提記等。別則教理等皆別。圓則教理等皆圓。又此四教。由三觀起。從假入空。析體異故。有初二教起。從空入假。從假入中。有別教起。三觀一心中得。有圓教起。又此四教不局定一部。一部之中容有多故。又更以四種化儀收之。謂頓。漸。不定。祕密。頓漸同前岌公。後二謂一音異解。若互相知。名為不定。互不相知。即名祕密。

三唐初海東元曉法師。亦立四教。一二乘別教。如四諦緣起經等。二三乘通教。如般若深密經等。三一乘分教。如梵網經等。四一乘滿教。如華嚴經等。然三乘共學。名三乘教。於中未明法空。名別相教。說諸法空。是為通教。不共二乘。名一乘教。於中未顯普法。名隨分教。具明普法。名圓滿教。然此大師大同天台。但合別圓。加一乘分耳。

四賢首弟子苑公。依寶性論立四種教。論云。四種眾生。不識如來藏。如生盲人。一者凡夫。二者聲聞。三者辟支佛。四者初心菩薩。言四教者。一迷真異執教。當彼凡夫。二真一分半教。當彼二乘。三真一分滿教。當彼初心菩薩。四真具分滿教。即當彼識如來藏者。初教謂諸外道。迷於真理。廣起異執。二謂小乘。於真如理。隨緣不變二分義中。唯說生空所顯之理。故名為半。如涅槃半字。三謂但得不變。不得隨緣。故名一分。而雙辯二空。故名為滿。四由具隨緣不變二義具分。廣如彼說。
第五判五教。略有二家。一波頗三藏。判一四諦教。謂四阿含等。二無相教。謂諸般若。三觀行教。謂華嚴經。四安樂教。謂涅槃經。說常樂故。五守護教。謂大集經。說守護正法事故。

二賢首大師。所立五教。至下當知。

:::{.text-sectioning}
△二西域。
:::

第二明西域者。即今性相二宗元出彼方。故名西域。謂那爛陀寺同時二大德。一名戒賢。二名智光。戒賢遠承彌勒無著。近踵護法難陀。依深密等經。瑜伽等論。立三種教。以法相大乘而為了義。即唐三藏之所師宗。謂佛初于鹿苑。轉四諦小乘法輪。說諸有為法皆從緣生。以破外道自性因等。又緣生無我。翻外有我。然猶未說法無我理。即四阿含等是。第二時中。雖依遍計所執。而諸法自性皆空。翻彼小乘。然依他圓成猶未說有。即諸部般若等經。第三時中。就大乘正理具說三性。三無性等。方為盡理。即解深密經等。是故於彼三時。初墮有邊。次墮空邊。俱非了義。後時具說。遍計性空。餘二為有。契會中道。方為了義。

二智光論師。遠承文殊龍樹。近稟青目清辯^[皆中觀論師]。依般若等經。中觀等論。亦立三時教。以無相大乘為真了義。謂佛初鹿苑說小。明心境俱有。次於中時。於彼中根說法相大乘。境空心有。唯識道理。以根猶劣。未能全入平等真空故。後第三時。為上根說無相大乘。辯心境俱空。平等一味。為真了義。

賢首大師立五教。一小乘教。二大乘始教。三終教。四頓教。五圓教。初即天台藏教。若約所說法相者。但說七十五法。但說人空。不說法空。縱少說法空。亦不明顯。但依六識三毒建立染淨根本。故阿含云。貪恚愚痴。是世間根本等。未盡法源。故多諍論。部執不同。

二大乘始教。亦名分教。以深密第二第三時。同許定性二乘及諸闡提。俱不成佛。故今合之總為一教。未盡大乘法理。故立為初。有不成佛。故名為分。廣說法相。少說法性。所說法性。即法相數。所說法數。擇廣成略。猶有百法。決擇分明。故少諍論。說有八識。唯是生滅。依生滅識。建立生死及涅槃因。法爾種子。有無永別。既所立識唯業惑生。故所立真如常恒不變。不許隨緣。

三終教者。亦名實教。定性二乘。無性闡提。悉當成佛。方盡大乘至極之說。故立為終。以稱實理。故名為實。少說法相。多說法性。所說法相。亦會歸於性。所立八識。通如來藏。隨緣成立。生滅與不生滅和合。而成非一非異。一切眾生平等一性。但是真如隨緣成立。依他無性。即是圓成。一理齊平。故說生界佛界不增不減。如是義類亦有眾多。廣如華嚴懸談說。

四頓教者。但一念不生。即名為佛。不依地位漸次而說。故立為頓。如思益云。得諸法正性者。不從一地至於一地。楞伽云。初地即為八。乃至無所有何次等。不同前漸次位修成。不同於後圓融具德。故立名頓。頓詮此理。故名頓教。總不說法相。唯辯真性。亦無八識差別之相。一切所有唯是妄想。一切法界唯是絕言。五法三自性皆空。八識二無我雙遣。訶教勸離。毀相泯心。生心即妄。不生即佛。亦無佛無不佛。無生無不生。如淨名默然。顯不二等。是其意也。

五圓教者。明一位即一切位。一切位即一位。是故十信滿心。即攝五位。成等正覺。依普賢法界。帝網重重。主伴具足。故名圓教。即華嚴經所說。唯是無盡法界。性海圓融。緣起無礙。相即相入。如因陀羅網。重重無際。微細相容。主伴無盡。十十法門各攝法界故。

已知五教收盡諸經。不知此經何教所攝。若以教攝經。正屬頓教。分屬終圓。若以經攝教。全收五教。更帶人天。以經中具足五教人天義理故。

:::{.text-sectioning}
△三義理分齊。
:::

三義理分齊者。已知此經正屬頓教。傍兼終圓。未委三教分齊如何。先明正屬頓教者。經中頓彰一心。直入無念。而成正觀。即此離念一心。是頓教分齊。起信論云。離念相者。等虗空界。即四法界之一真法界也。次明傍兼者。先明終教。終實大乘。即同教一乘。理事無礙法界始終十門。即其分齊。今此經中。純顯真如一心。不礙萬行修證。雖諸行歷然。不雜一心平等。是終實分齊義。次明圓教者。即別教一乘。備十玄門圓融具德。惟華嚴經。今此經中略具少分。故言分屬。經云。妙高山王納芥子。山王芥子不壞相。即十玄門中廣狹自在一門也。人天小乘無不具攝。分齊較淺。故不詳明。以上義理分齊竟。

:::{.text-sectioning}
△四教所被機。
:::

四教所被機者。已知此經義理深廣。未識被何等人。欲辨機宜。略分二門。第一料揀。第二普收。且初料揀者。復分為二。一明非機。有四。一無信非機。不信自心。不能成觀故。二凡愚非機。謂任運一生。不識道理故。三邪見非機。謂執著斷常。不達正理故。四定性非機。謂灰斷纏空。不發大心故。二明正機。亦四。一正信是機。肯信自心。能成正觀故。二智者是機。知因識果。樂欲修證故。三正見是機。了明心地。不淪斷常故。四發心是機。發菩提心。超出偏小故。

二普收者。一切眾生皆有佛性。有佛性者皆得作佛。雖發心有早晚。修證有前後。但有心地。俱是此經所被之機也。以上教所被機竟。

:::{.text-sectioning}
△五能詮教體。
:::

五能詮教體者。已知此經被機廣博。未委能詮何為教體。今欲略明。啟為四門。一隨相門。二唯識門。三歸性門。四無礙門。先明隨相。一明能詮。二兼收所詮。以徒文無義。非教故。初明能詮者。即聲名句文。以音聲為主。名則次第行列。詮法自性。句則次第安布。詮法差別。文則次第聯合。為上二所依。此名句文三。為聲上詮表。以唯聲則不能詮義。唯名句文則無自體。兼收此四。方成教體。二所詮義者。此聲名句文。若無所詮之義。如海篇字彚。非是聖教。若獨義無文。則理無可憑。必也義隨於文。文依於義。文義相資。乃成教體。今經從如是我聞至終。是聲名句文體。修證心地觀門等。是所詮義體。二者相隨。教體備矣。以文義皆屬相。故曰隨相門也。

二唯識門者。以文義皆從識變。有本影四句。一唯本無影。即小乘教。不知教從識現。謂佛實說法故。二亦本亦影。即始教。謂佛說文義。從妙觀察淨識所現。名本質教。聞者識上所變文義。名影像教。諸佛眾生互為增上緣故。三唯影無本。即終教。以離眾生自心。更無有佛。唯大悲大智為增上緣。令彼根熟眾生心中現佛說法。是故佛教。全是眾生心中影像。四非本非影。即頓教。非唯心外無佛。眾生心中影像亦空。以性本絕言。即不教之教。無說無聞。是名真說真聞。今經約終頓二教。以眾生二乘。初心菩薩等。感自心中見佛。為說心地觀法。說即無說。聽亦無聽。是唯識體。

三歸性門者。前以影本攝歸八識。今以八識攝歸一心。則性為教體。一心者即真如自體也。從此真如流出教法。故會相歸性。所謂重頌如。授記如。十二分一切皆如。以上展轉推原。譬如物不離夢。夢不離人。圓覺疏云。生法本無。一切惟識。識如夢幻。惟是一心。則以自心為教體。此經佛說三界以心為主。即觀此心。是自性教體。

四無礙門者。有二。即理事無礙。事事無礙。如說即無說。無說即說。皆理事無礙義。如言一即是多。多不礙一。皆事事無礙義。心境理事皆交徹故。故名無礙。今此經以真如心地。不礙種種修證。即心境理事不礙為教體也。

:::{.text-sectioning}
△六宗趣通別。
:::

六宗趣通局者。已知此經能詮之體。未識所宗其義云何。語之所尚曰宗。宗之所歸曰趣。欲明宗趣。有通有局。通論佛教以因緣為宗。因緣者。揀異無因邪因。一代時教因緣攝盡。故云通也。局就當經。略為四說。一正宗之初。佛說心地薰修。為言之所宗。得成菩提。為歸趣。二佛令報恩。為言之所宗。引發菩提心。為歸趣。三智光長者重請說四恩為請法之宗。次父子求佛出家。為請法之趣。四如來說蘭若。令依止為宗。修觀頓悟。究竟菩提為趣。此略取大章。指明歸趣。以上宗趣通局竟。

:::{.text-sectioning}
△七品目次第。
:::

七品類次第者。如來說法必借緣興。放光現瑞。騰疑請法。佛未出定。菩薩旁通。為發起因緣。故曰序品。二佛既出定。說心地法門。五百長者不欲聞大。權說四恩。故有報恩品。次智光長者請重說四恩。故有四恩之重頌。三佛讚出家。令離纏縛。故有厭捨品。四佛令安住四法。遠離貪求。是無垢性。故說無垢性品。五廣說蘭若。勸教修證。故有阿蘭若品。六世尊復說蘭若功德。開導修證。故有離世間品。七彌勒請觀。佛令厭身修道。故有厭身品。八佛答彌勒難問。發明諸度。故有波羅蜜品。九由住蘭若修勝功德。故有功德莊嚴品。十由佛談心地薰修。未及詳明。故有觀心品。十一心地已說。觀法已明。復勸發心。助修神呪。故有發心品。十二廣明印呪。佐助觀功。護持行人。疾至菩提。故有成佛品。十三心地始終。因果理行具備詳明。付囑當機。流通後世。故有囑累品。以上品目次第竟。

:::{.text-sectioning}
△八傳譯時年。
:::

八傳譯朝代者。既知此經品目如此。未知譯自何時。此經梵本。來自唐高宗朝。師子國人所獻。祕於中禁。未及翻譯。歷十主。至憲宗嗣位。始出其梵本。詔罽賓三藏般若主譯。京都義學。共八人證譯。諫議孟簡等。四人潤文。勒成一部。八卷一十三品。夫佛生天竺。經皆梵言。不假翻譯孰能通意。翻譯由人。故出之以重元勳也。雖人能弘道。非嘉會之良時。佛法之妙應不成。信乎法不虗應。應必有時矣。名翻譯朝代者。重時也。以上八義門竟。
